name: fix
description: Creates an issue of type fix, used to target simple changes or bugs.
title: "fix: "
labels: []
projects: ["koble-mx/3"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: This input is important to understant why the task should be done. There is no point in doing a fix that serves no purpose to the final user.
      placeholder: As a user I want to download a csv report...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Make sure to describe with great detail what should be done in this task to be marked as done. Anyone in the team should be able to read it and completely understand what do to.
      placeholder: What should be accomplished?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
